### PR TITLE
Update to 1.18.2

### LINKED ISSUE #15: 1.18.2 causes a `RuntimeException` when loaded
Running on the the latest fabric server for 1.18.2. Looks like some minor changes that need to be made. I might be able to take a closer look later on.

<details>
    <summary>Crash Report (click to expand)</summary>

    ---- Minecraft Crash Report ----
    // There are four lights!

    Time: 2/28/22, 7:12 PM
    Description: Exception in server tick loop

    java.lang.RuntimeException: Mixin transformation of net.minecraft.class_2881 failed
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:252)
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150)
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at net.minecraft.class_3218.<init>(class_3218.java:244)
        at net.minecraft.server.MinecraftServer.method_3786(MinecraftServer.java:415)
        at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:330)
        at net.minecraft.class_3176.method_3823(class_3176.java:180)
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
        at java.base/java.lang.Thread.run(Thread.java:833)
    Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247)
        ... 10 more
    Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method adjustExitPortalLocation(ZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V in mixins.protosky.json:EnderDragonFightMixin from mod protosky failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap protosky-refmap.json
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
        at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1385)
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052)
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
        ... 13 more

    A detailed walkthrough of the error, its code path and all known details is as follows:
    ---------------------------------------------------------------------------------------

    -- System Details --
    Details:
        Minecraft Version: 1.18.2
        Minecraft Version ID: 1.18.2
        Operating System: Windows 11 (amd64) version 10.0
        Java Version: 17.0.2, Azul Systems, Inc.
        Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Azul Systems, Inc.
        Memory: 2137836432 bytes (2038 MiB) / 2579496960 bytes (2460 MiB) up to 4294967296 bytes (4096 MiB)
        CPUs: 24
        Processor Vendor: GenuineIntel
        Processor Name: 12th Gen Intel(R) Core(TM) i9-12900K
        Identifier: Intel64 Family 6 Model 151 Stepping 2
        Microarchitecture: unknown
        Frequency (GHz): 3.19
        Number of physical packages: 1
        Number of physical CPUs: 16
        Number of logical CPUs: 24
        Graphics card #0 name: NVIDIA GeForce RTX 3080 Ti
        Graphics card #0 vendor: NVIDIA (0x10de)
        Graphics card #0 VRAM (MB): 4095.00
        Graphics card #0 deviceId: 0x2208
        Graphics card #0 versionInfo: DriverVersion=30.0.14.7141
        Memory slot #0 capacity (MB): 16384.00
        Memory slot #0 clockSpeed (GHz): 4.80
        Memory slot #0 type: Unknown
        Memory slot #1 capacity (MB): 16384.00
        Memory slot #1 clockSpeed (GHz): 4.80
        Memory slot #1 type: Unknown
        Virtual memory max (MB): 37373.29
        Virtual memory used (MB): 17362.18
        Swap memory total (MB): 4864.00
        Swap memory used (MB): 2.96
        JVM Flags: 1 total; -Xmx4G
        Server Running: true
        Player Count: 0 / 20; []
        Data Packs: vanilla
        World Generation: Stable
        Is Modded: Definitely; Server brand changed to 'fabric'
        Type: Dedicated Server (map_server.txt)
</details>

### PR DESCRIPTION
**Pull request by ghost**
Updates the mod to support 1.18.2 - mostly just changes to mixins. Also removed some unneeded methods from utility classes. Closes #15

### CODE REVIEW

**Comment by polarbub** [comment]
I'm done my own version of the updates and just adding some optimizations, so I won't merge this. I will reference this though to see if I did it correctly. Also it's only a bug fix version bump.

**Comment by polarbub** [comment]
Never mind my own work is taking too long, I'm going to merge this. Thanks rybot!

**Comment by polarbub** [comment]
It doesn't generate end portals, can you fix that?

**Comment by ghost** [comment]
huh, my bad. I'll fix it some time this week

**Comment by polarbub** [comment]
I did this on my own. Thanks for doing this on your own before I could, I didn't get around to fixing this before I finished mine. :)

**Pull request closed without merging**
