### PR TITLE
1.18 Update

### PR DESCRIPTION
**Pull request by aqnox**
WIP. Help appreciated

TODO:
- [x] Fix compile issues
- [ ] Fix features overwriting generated chunks

### CODE REVIEW

**Comment by polarbub** [comment]
Are you on discord?

**Comment by aqnox** [comment]
@polarbub yeah, FrostByte#4166

**Comment by polarbub** [comment]
Is `640336770961113109` your discord ID?

**Comment by AlejandroRI** [comment]
Hey, only you need 1 thing, change "method_20613" for "method_20614" in your ChunkStatusMixin class

**Comment by polarbub** [comment]
Does that fix the structure errors?

**Comment by polarbub** [comment]
Okay, That works great, Thanks! Although entities aren't being deleted correctly, I still have to look into that.

**Comment by polarbub** [comment]
Okay, the entities issue is fixed, I'll push and release the new version tomorrow.

**Comment by polarbub** [comment]
I borked GitHub with some CLI stuff, Going to merge a different way

**Comment by aqnox** [comment]
Awesome! I've been away but this is great progress!

**Comment by aqnox** [comment]
@polarbub My discord id is `215486695095795714` I think. What's it for?

**Comment by polarbub** [comment]
I have a different FrostByte in one of my discord and I wanted the id to compare to see if it was you.

**Pull request closed without merging**
